---
bibliography: bibliography.bib
documentclass: article
fontsize: 11pt
geometry: margin=2cm
header-includes:
- \usepackage[brazil, english, portuguese]{babel}
- \usepackage[utf8]{inputenc}
- \usepackage[T1]{fontenc}
- \usepackage[fixlanguage]{babelbib}
- \usepackage{longtable}
- \usepackage{amsfonts}
- \usepackage{amssymb}
- \usepackage{amsmath}
- \usepackage{subcaption}
- \usepackage{booktabs}
- \usepackage{caption}
- \usepackage{float}
output:
  pdf_document:
    fig_crop: no
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE, 
  message = FALSE, 
  warning = FALSE,
  cache = FALSE,
  #engine.path = list(r = '', pyton = ''), 
  tidy = "formatR", tidy.opts = list(width.cutoff = 60), #tidy = "styler", 
  fig.align = "center", fig.pos = "h", fig.height = 3, fig.width = 5
  )
options(
  digits = 2, 
  OutDec = ".", 
  digits = 2, scipen = 4, 
  xtable.comment = FALSE
  )
```


\begin{titlepage} 

\begin{center} 
{\large Universidade Estadual de Campinas}\\[0.2cm] 
{\large Instituto de Matemática, Estatística e Computação Científica}\\[0.2cm] 
{\large Departamento de Estatística - ME714}\\[4cm]

{\bf \huge Desgaste de funcionários e suas possíveis causas: uma análise e previsão utilizando árvore de decisão ID3}\\
{\bf \Large Trabalho Final - Grupo 14}\\[6cm]




{\large Wesley Cabral Alvez, RA: 225825}\\[0.2cm]
{\large Nathan Brusamarello De Souto, RA: 222854}\\[0.2cm]
{\large Helton Marinho De Ávila, RA: 174471}\\[0.2cm]
{\large Natainá Novaes Silva Barbosa, RA: 242290}\\[1cm]

{\large Prof. Dra. Hildete Prisco Pinheiro}\\[1cm]

{\large Campinas}\\[0.2cm]
{\large 2021}
\end{center}

\end{titlepage}

\begin{abstract}
Resumo Resumo Resumo

\end{abstract}

\newpage

\tableofcontents

\newpage


# Introdução

Abrir a discussão sobre o desgaste dos funcionários - O que é isso? O que ela afeta? É uma realidade no Mundo, no Brasil?

\cite{koerich, patel2014decisiontree, singh2014analysis}.

--> Falar também sobre o método de arvóre de decisão ID3 (porque utilizar? vantagens?)

# Objetivo

"Sabendo da realidade do desgate de funcinários e seus problemas, foi (ou será) realizado uma análise e previsão ..."

# Dados

Vamos traduzir todos?

Descrição dos dados com as devidas análises explorátorias (analise geral por cima de todos, descrição dos dados e relação com o desgaste).

Tabelas de contingência?

# Metodologia 

--> Parte mais importante segundo a hildete

- Arvore de Decisao ID3 (explicar cada detalhe)
  - Entropia
  - Information Gain

- Validação utilizada --> hold-out ou k-folds?

# Aplicação

Mostrar os resultados da aplicação do modelo

# Conclusão

Comentar os resultados (tendência para não atrito)

\clearpage
\bibliographystyle{plain}
\bibliography{bibliography}
